import type { WorldGeoEntityId, WorldGeoNode } from "@/lib/reality-graph/types";
import { FREQUENT_TRAVEL_GEO_NODES } from "@/lib/reality-graph/frequent-travel-geo";

/**
 * Seed World Graph (Japan · Korea travel MVP). Catalog SSOT — not LLM memory.
 * Frequent stations/landmarks: `frequent-travel-geo.ts`. Keep ids stable.
 */
export const WORLD_GEO_SEED: readonly WorldGeoNode[] = [
  {
    id: "geo:world",
    kind: "world",
    parentId: null,
    labels: { ko: "세계", en: "World" },
    centroid: { lat: 0, lng: 0 },
    boundary: null,
    ianaTimeZone: null,
    currencyCode: null,
    primaryLanguage: null,
  },
  {
    id: "geo:asia",
    kind: "continent",
    parentId: "geo:world",
    labels: { ko: "아시아", en: "Asia" },
    centroid: { lat: 34, lng: 100 },
    boundary: null,
    ianaTimeZone: null,
    currencyCode: null,
    primaryLanguage: null,
  },
  {
    id: "geo:jp",
    kind: "country",
    parentId: "geo:asia",
    labels: {
      ko: "일본",
      en: "Japan",
      local: "日本",
      aliases: ["japan", "일본", "jp", "日本"],
    },
    centroid: { lat: 36.2048, lng: 138.2529 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo",
    kind: "metropolis",
    parentId: "geo:jp",
    labels: {
      ko: "도쿄도",
      en: "Tokyo Metropolis",
      local: "東京都",
      aliases: [
        "tokyo",
        "도쿄",
        "동경",
        "tokyo metropolis",
        "도쿄도",
        "東京都",
        "tokyo-to",
        "東京都",
      ],
    },
    centroid: { lat: 35.6762, lng: 139.6503 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:tokyo-station",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "도쿄역",
      en: "Tokyo Station",
      local: "東京駅",
      aliases: [
        "도쿄역",
        "동경역",
        "tokyo station",
        "tokyo-station",
        "東京駅",
        "とうきょうえき",
        "tokyo sta",
      ],
    },
    centroid: { lat: 35.681236, lng: 139.767125 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:shinjuku",
    kind: "ward",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "신주쿠구",
      en: "Shinjuku City",
      local: "新宿区",
      aliases: ["shinjuku", "신주쿠", "新宿", "shinjuku-ku", "신주쿠구"],
    },
    centroid: { lat: 35.6938, lng: 139.7034 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:shinjuku:kabukicho",
    kind: "neighborhood",
    parentId: "geo:jp:tokyo:shinjuku",
    labels: {
      ko: "가부키초",
      en: "Kabukicho",
      local: "歌舞伎町",
      aliases: ["kabukicho", "가부키초", "歌舞伎町", "kabuki-cho"],
    },
    centroid: { lat: 35.6951, lng: 139.7028 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:shibuya",
    kind: "ward",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "시부야구",
      en: "Shibuya City",
      local: "渋谷区",
      aliases: ["shibuya", "시부야", "渋谷", "shibuya-ku"],
    },
    centroid: { lat: 35.6595, lng: 139.7004 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:ginza",
    kind: "district",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "긴자",
      en: "Ginza",
      local: "銀座",
      aliases: ["ginza", "긴자", "銀座"],
    },
    centroid: { lat: 35.6717, lng: 139.765 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:akihabara",
    kind: "district",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "아키하바라",
      en: "Akihabara",
      local: "秋葉原",
      aliases: ["akihabara", "아키하바라", "秋葉原", "akiba"],
    },
    centroid: { lat: 35.6984, lng: 139.7731 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:osaka",
    kind: "prefecture",
    parentId: "geo:jp",
    labels: {
      ko: "오사카부",
      en: "Osaka Prefecture",
      local: "大阪府",
      aliases: ["osaka", "오사카", "大阪", "osaka prefecture", "오사카부"],
    },
    centroid: { lat: 34.6937, lng: 135.5023 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:osaka:namba-station",
    kind: "poi",
    parentId: "geo:jp:osaka",
    labels: {
      ko: "난바역",
      en: "Namba Station",
      local: "難波駅",
      aliases: [
        "난바역",
        "난바",
        "namba",
        "namba station",
        "難波",
        "難波駅",
        "なんば",
        "난바 역",
      ],
    },
    // APA Namba / Nankai Namba area
    centroid: { lat: 34.6654, lng: 135.5019 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:osaka:umeda-station",
    kind: "poi",
    parentId: "geo:jp:osaka",
    labels: {
      ko: "우메다역",
      en: "Umeda Station",
      local: "梅田駅",
      aliases: [
        "우메다역",
        "우메다",
        "umeda",
        "umeda station",
        "梅田",
        "梅田駅",
        "うめだ",
        "오사카역",
        "osaka station",
      ],
    },
    centroid: { lat: 34.7055, lng: 135.4983 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:kyoto",
    kind: "prefecture",
    parentId: "geo:jp",
    labels: {
      ko: "교토부",
      en: "Kyoto Prefecture",
      local: "京都府",
      aliases: ["kyoto", "교토", "京都", "kyoto prefecture", "교토부"],
    },
    centroid: { lat: 35.0116, lng: 135.7681 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:hokkaido",
    kind: "prefecture",
    parentId: "geo:jp",
    labels: {
      ko: "홋카이도",
      en: "Hokkaido",
      local: "北海道",
      aliases: ["hokkaido", "홋카이도", "北海道", "sapporo"],
    },
    centroid: { lat: 43.0618, lng: 141.3545 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:cn",
    kind: "country",
    parentId: "geo:asia",
    labels: {
      ko: "중국",
      en: "China",
      local: "中国",
      aliases: ["china", "중국", "cn", "中国", "중화인민공화국"],
    },
    centroid: { lat: 35.8617, lng: 104.1954 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:cn:shanghai",
    kind: "metropolis",
    parentId: "geo:cn",
    labels: {
      ko: "상하이",
      en: "Shanghai",
      local: "上海",
      aliases: ["shanghai", "상하이", "상해", "上海"],
    },
    centroid: { lat: 31.2304, lng: 121.4737 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:cn:shanghai:pudong",
    kind: "district",
    parentId: "geo:cn:shanghai",
    labels: {
      ko: "푸동",
      en: "Pudong",
      local: "浦东",
      aliases: ["pudong", "푸동", "浦东", "푸동신구", "pudong new area"],
    },
    centroid: { lat: 31.2215, lng: 121.5444 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:cn:shanghai:hongqiao",
    kind: "district",
    parentId: "geo:cn:shanghai",
    labels: {
      ko: "홍차오",
      en: "Hongqiao",
      local: "虹桥",
      aliases: ["hongqiao", "홍차오", "虹桥", "hongqiao district"],
    },
    centroid: { lat: 31.1979, lng: 121.334 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:cn:shanghai:pvg",
    kind: "poi",
    parentId: "geo:cn:shanghai",
    labels: {
      ko: "푸동 국제공항",
      en: "Shanghai Pudong International Airport",
      local: "上海浦东国际机场",
      aliases: [
        "pvg",
        "PVG",
        "푸동",
        "푸동공항",
        "푸동 공항",
        "푸동국제공항",
        "푸동 국제공항",
        "浦东机场",
        "浦东国际机场",
        "pudong airport",
        "shanghai pudong",
      ],
    },
    centroid: { lat: 31.1443, lng: 121.8083 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:cn:shanghai:sha",
    kind: "poi",
    parentId: "geo:cn:shanghai",
    labels: {
      ko: "홍차오 국제공항",
      en: "Shanghai Hongqiao International Airport",
      local: "上海虹桥国际机场",
      aliases: [
        "sha",
        "SHA",
        "홍차오",
        "홍차오공항",
        "홍차오 공항",
        "홍차오국제공항",
        "홍차오 국제공항",
        "虹桥机场",
        "虹桥国际机场",
        "hongqiao airport",
        "shanghai hongqiao",
      ],
    },
    centroid: { lat: 31.1979, lng: 121.3364 },
    boundary: null,
    ianaTimeZone: "Asia/Shanghai",
    currencyCode: "CNY",
    primaryLanguage: "zh",
  },
  {
    id: "geo:jp:nrt",
    kind: "poi",
    parentId: "geo:jp",
    labels: {
      ko: "나리타 공항",
      en: "Narita International Airport",
      local: "成田国際空港",
      aliases: ["nrt", "narita", "나리타", "成田", "나리타공항", "나리타 공항"],
    },
    centroid: { lat: 35.772, lng: 140.3929 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:hnd",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "하네다 공항",
      en: "Haneda Airport",
      local: "羽田空港",
      aliases: ["hnd", "haneda", "하네다", "羽田", "하네다공항", "하네다 공항"],
    },
    centroid: { lat: 35.5494, lng: 139.7798 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:kix",
    kind: "poi",
    parentId: "geo:jp:osaka",
    labels: {
      ko: "간사이 공항",
      en: "Kansai International Airport",
      local: "関西国際空港",
      aliases: [
        "kix",
        "kansai",
        "간사이",
        "関西空港",
        "간사이공항",
        "간사이 공항",
        "간사이 국제공항",
        "간사이국제공항",
        "kansai international",
        "kansai airport",
      ],
    },
    centroid: { lat: 34.4347, lng: 135.244 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:disneyland",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "도쿄 디즈니랜드",
      en: "Tokyo Disneyland",
      local: "東京ディズニーランド",
      aliases: ["disneyland", "디즈니랜드", "도쿄디즈니랜드", "東京ディズニーランド"],
    },
    centroid: { lat: 35.6329, lng: 139.8804 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:disneysea",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "도쿄 디즈니씨",
      en: "Tokyo DisneySea",
      local: "東京ディズニーシー",
      aliases: ["disneysea", "디즈니씨", "東京ディズニーシー"],
    },
    centroid: { lat: 35.6267, lng: 139.8851 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:osaka:usj",
    kind: "poi",
    parentId: "geo:jp:osaka",
    labels: {
      ko: "유니버설 스튜디오 재팬",
      en: "Universal Studios Japan",
      local: "ユニバーサル・スタジオ・ジャパン",
      aliases: [
        "usj",
        "universal studios",
        "universal studios japan",
        "유니버설",
        "유니버셜",
        "유니버설 스튜디오",
        "유니버셜 스튜디오",
        "유니버설 스튜디오 재팬",
        "유니버셜 스튜디오 재팬",
        "ユニバーサル",
      ],
    },
    centroid: { lat: 34.6654, lng: 135.4323 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:sensoji",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "센소지",
      en: "Senso-ji",
      local: "浅草寺",
      aliases: ["sensoji", "senso-ji", "센소지", "浅草寺", "아사쿠사 절"],
    },
    centroid: { lat: 35.7148, lng: 139.7967 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:ueno-park",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "우에노 공원",
      en: "Ueno Park",
      local: "上野公園",
      aliases: ["ueno park", "우에노공원", "上野公園"],
    },
    centroid: { lat: 35.7146, lng: 139.7715 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:skytree",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "도쿄 스카이트리",
      en: "Tokyo Skytree",
      local: "東京スカイツリー",
      aliases: ["skytree", "스카이트리", "東京スカイツリー"],
    },
    centroid: { lat: 35.7101, lng: 139.8107 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:jp:tokyo:shibuya-crossing",
    kind: "poi",
    parentId: "geo:jp:tokyo",
    labels: {
      ko: "시부야 스크램블",
      en: "Shibuya Crossing",
      local: "渋谷スクランブル交差点",
      aliases: ["shibuya crossing", "시부야스크램블", "渋谷スクランブル"],
    },
    centroid: { lat: 35.6595, lng: 139.7005 },
    boundary: null,
    ianaTimeZone: "Asia/Tokyo",
    currencyCode: "JPY",
    primaryLanguage: "ja",
  },
  {
    id: "geo:kr",
    kind: "country",
    parentId: "geo:asia",
    labels: {
      ko: "대한민국",
      en: "South Korea",
      local: "대한민국",
      aliases: ["korea", "한국", "대한민국", "kr", "south korea"],
    },
    centroid: { lat: 35.9078, lng: 127.7669 },
    boundary: null,
    ianaTimeZone: "Asia/Seoul",
    currencyCode: "KRW",
    primaryLanguage: "ko",
  },
  {
    id: "geo:kr:seoul",
    kind: "metropolis",
    parentId: "geo:kr",
    labels: {
      ko: "서울",
      en: "Seoul",
      local: "서울",
      aliases: ["seoul", "서울", "서울특별시", "서울시"],
    },
    centroid: { lat: 37.5665, lng: 126.978 },
    boundary: null,
    ianaTimeZone: "Asia/Seoul",
    currencyCode: "KRW",
    primaryLanguage: "ko",
  },
  {
    id: "geo:kr:icn",
    kind: "poi",
    parentId: "geo:kr",
    labels: {
      ko: "인천공항",
      en: "Incheon International Airport",
      local: "인천국제공항",
      aliases: ["icn", "incheon", "인천", "인천공항", "인천국제공항"],
    },
    centroid: { lat: 37.4602, lng: 126.4407 },
    boundary: null,
    ianaTimeZone: "Asia/Seoul",
    currencyCode: "KRW",
    primaryLanguage: "ko",
  },
  {
    id: "geo:kr:gmp",
    kind: "poi",
    parentId: "geo:kr:seoul",
    labels: {
      ko: "김포공항",
      en: "Gimpo International Airport",
      local: "김포국제공항",
      aliases: ["gmp", "gimpo", "김포", "김포공항"],
    },
    centroid: { lat: 37.5583, lng: 126.7906 },
    boundary: null,
    ianaTimeZone: "Asia/Seoul",
    currencyCode: "KRW",
    primaryLanguage: "ko",
  },
  ...FREQUENT_TRAVEL_GEO_NODES,
] as const;

const BY_ID = new Map<WorldGeoEntityId, WorldGeoNode>(
  WORLD_GEO_SEED.map((node) => [node.id, node]),
);

export function getWorldGeoNode(id: WorldGeoEntityId): WorldGeoNode | null {
  return BY_ID.get(id) ?? null;
}

export function listWorldGeoChildren(parentId: WorldGeoEntityId): WorldGeoNode[] {
  return WORLD_GEO_SEED.filter((node) => node.parentId === parentId);
}

export function listWorldGeoSeed(): readonly WorldGeoNode[] {
  return WORLD_GEO_SEED;
}
